version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    expose:
      - "5252"
    networks:
      - softy-pinko-network

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    expose:
      - "9000"
    depends_on:
      - back-end
    networks:
      - softy-pinko-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
    networks:
      - softy-pinko-network

networks:
  softy-pinko-network:
    driver: bridge 